# Generated by Django 4.0.5 on 2022-06-15 11:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCadeira', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(default=1)),
                ('etcs', models.IntegerField(default=0)),
                ('link_cadeira', models.URLField(blank=True)),
                ('rank', models.CharField(max_length=6)),
                ('ano', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Quizz/')),
            ],
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('linkNot', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='pontuacaoquizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('Q1', models.CharField(max_length=200, null=True)),
                ('Q2', models.CharField(max_length=200, null=True)),
                ('Q3', models.CharField(max_length=200, null=True)),
                ('Q4', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitLink', models.CharField(default='https://github.com/rodrigoamaro22004525', max_length=200)),
                ('nome', models.CharField(max_length=50)),
                ('linguagens', models.CharField(max_length=50)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('acronimo', models.CharField(max_length=5)),
                ('ano', models.DateTimeField(default=0.000211954217888936)),
                ('autor', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='media/')),
                ('linkYo', models.CharField(default='https://github.com/rodrigoamaro22004525?tab=repositories', max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.post')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
