# Generated by Django 4.0.4 on 2022-05-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('nomeDoProjeto', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nomeDoProjeto'],
            },
        ),
    ]
