# Generated by Django 4.0.4 on 2022-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='name',
            field=models.CharField(default='objects', max_length=50),
        ),
    ]
