# Generated by Django 4.0.5 on 2022-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCadeira', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(default=1)),
                ('etcs', models.IntegerField(default=0)),
                ('link_cadeira', models.URLField(blank=True)),
                ('rank', models.CharField(max_length=6)),
            ],
        ),
    ]
