# Generated by Django 4.0.4 on 2022-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
