# Generated by Django 4.0.4 on 2022-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacaoquizz',
            name='name',
        ),
        migrations.AddField(
            model_name='pontuacaoquizz',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
