# Generated by Django 4.0.5 on 2022-06-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologias',
            name='tipo',
        ),
    ]
