# Generated by Django 4.0.4 on 2022-06-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_pontuacaoquizz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
