# Generated by Django 4.0.5 on 2022-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_licenciatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='ano',
            field=models.IntegerField(default=1),
        ),
    ]
