# Generated by Django 4.0.4 on 2022-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, upload_to='Quizz/'),
        ),
    ]
