# Generated by Django 4.0.4 on 2022-06-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_pontuacaoquizz_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontuacaoquizz',
            old_name='nome',
            new_name='name',
        ),
    ]
