# Generated by Django 4.0.4 on 2022-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('data', models.IntegerField(max_length=20)),
                ('linguagens', models.CharField(max_length=50)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Programacao',
        ),
    ]
