# Generated by Django 4.0.5 on 2022-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_licenciatura_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='linha',
            field=models.IntegerField(default=1),
        ),
    ]
