# Generated by Django 4.0.5 on 2022-06-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_imagem_projetos_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tecnologias',
        ),
    ]
