# Generated by Django 4.0.5 on 2022-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_tecnologias'),
    ]

    operations = [
        migrations.CreateModel(
            name='tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('acronimo', models.CharField(max_length=5)),
                ('ano', models.DateTimeField(default=0.000211954217888936)),
                ('autor', models.CharField(max_length=50)),
                ('linkYo', models.CharField(default='https://github.com/rodrigoamaro22004525?tab=repositories', max_length=200)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
    ]
