# Generated by Django 4.0.5 on 2022-06-17 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tecnologias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologias',
            name='ano',
        ),
        migrations.AddField(
            model_name='tecnologias',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tecnologias',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
