# Generated by Django 4.0.5 on 2022-06-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projetos_gitlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='linha',
        ),
    ]
