# Generated by Django 4.0.4 on 2022-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_projetos_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='portfolio/static/images/'),
        ),
    ]
