# Generated by Django 4.0.4 on 2022-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_projetos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
